# Generated by Django 5.1 on 2024-08-08 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateNaissance', models.DateField()),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonelAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=50)),
                ('dateEntre', models.DateField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=50)),
                ('isDoctore', models.BooleanField(default=False)),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.personnel')),
            ],
        ),
    ]
