# Generated by Django 5.1 on 2024-08-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreatetion', models.DateField(auto_now=True)),
                ('antecedentsMedicaux', models.TextField(blank=True, max_length=1000)),
                ('alergies', models.TextField(blank=True, max_length=1000)),
                ('medicamentEncoure', models.TextField(blank=True, max_length=1000, null=True)),
                ('groupeSanguin', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsiteMedicaments', models.TextField(max_length=1000)),
                ('duree', models.CharField(max_length=100)),
                ('dosage', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOperation', models.TextField(max_length=200)),
                ('dateOperation', models.DateField()),
                ('delaisDateOperation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateConsultation', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(max_length=200)),
                ('diagnostic', models.CharField(max_length=1000)),
                ('dossierMedical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=20)),
                ('adresseEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='patients.dossiermedical')),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='utilisateurs.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePrescription', models.DateField(auto_now_add=True)),
                ('dossierMedical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeExamen', models.CharField(max_length=100)),
                ('consigne', models.TextField(blank=True, max_length=1000)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.prescription')),
            ],
        ),
    ]
