# Generated by Django 5.1 on 2024-08-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='dossierMedical',
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dossierMedical',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionDossier', to='patients.dossiermedical'),
        ),
    ]
