# Generated by Django 5.1 on 2024-08-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_consultation_dossiermedical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pouls',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='taille',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='tension_art',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
