# Generated by Django 5.1 on 2024-08-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_personnel'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRendezVous', models.DateField()),
                ('datePriseRendezVous', models.DateField(auto_now=True)),
                ('motif', models.TextField(max_length=200)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecinConcerner', to='utilisateurs.personnelmedical')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientConcerner', to='patients.patient')),
            ],
        ),
    ]
