# Generated by Django 5.1 on 2024-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rendezvous_heurrendezvous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='heurRendezVous',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='dateRendezVous',
            field=models.DateTimeField(),
        ),
    ]
