# Generated by Django 5.1 on 2024-08-15 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_rendezvous_heurrendezvous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='dateRendezVous',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_heure',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
