# Generated by Django 5.1 on 2024-08-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_rendezvous_daterendezvous_rendezvous_actif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='lsiteMedicaments',
            new_name='nomMedicament',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dossierMedical',
        ),
        migrations.AddField(
            model_name='consultation',
            name='dureeSymptome',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='patients.prescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptome',
            field=models.TextField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='prescription',
            name='examen',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='patients.examen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicament',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='patients.medicament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='operation',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='patients.operation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.diagnostic'),
        ),
    ]
