# Generated by Django 5.1 on 2024-08-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_diagnostic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.diagnostic'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.prescription'),
        ),
    ]
