# Generated by Django 5.1 on 2024-08-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_consultation_diagnostic_and_more'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='operation',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medecin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.personnelmedical'),
            preserve_default=False,
        ),
    ]
